version: 2
jobs:
  build:
    working_directory: /go/src/github.com/pottava/ecs-task-runner
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - setup_remote_docker
      - save_cache:
          key: pkg-cache
          paths:
            - "/go/pkg"
      - run: go get -u github.com/golang/dep/...
      - run: dep ensure
      - run: go get -u gopkg.in/alecthomas/gometalinter.v2
      - run:
          name: Run tests
          command: |
            gometalinter.v2 --install
            gometalinter.v2 --config=lint-config.json ./...
            go test -cover -bench -benchmem `go list ./...`
  release:
    working_directory: /go/src/github.com/pottava/ecs-task-runner
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Build and release
          command: |
            gox --osarch "linux/amd64 darwin/amd64 windows/amd64" -ldflags "-s -w -X main.date=$(date +%Y-%m-%d --utc) -X main.version=${CIRCLE_TAG} -X main.commit=${CIRCLE_SHA1}" -output "${GOPATH}/pkg/${CIRCLE_PROJECT_REPONAME}_{{.OS}}_{{.Arch}}"
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` $GOPATH/pkg/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
  release:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[1-9]+(\.[0-9]+)*/
